from typing import Dict, Any
import json
from langchain_core.messages import SystemMessage, HumanMessage
from core.llm import get_llm
from agents.state import GraphState

CRITIC_PROMPT = """You are the Critic and Evidence Validator Agent.
Review the collective evidence generated by the market, historical, technical, fundamental, entry, and risk agents.
Check for consistency, challenge unsupported claims (hallucinations), and determine if the overall evidence is valid.
You must output ONLY valid JSON matching the following schema exactly:
{
  "critic_feedback": "A concise paragraph summarizing your validation and pointing out any conflicts.",
  "is_valid": true or false
}
"""

async def critic_node(state: GraphState) -> Dict[str, Any]:
    llm = get_llm()
    
    # Collect all evidence
    evidence_bundle = {
        "market": state.get("market_regime_evidence"),
        "historical": state.get("historical_evidence"),
        "technical": state.get("technical_evidence"),
        "fundamental": state.get("fundamental_evidence"),
        "entry": state.get("entry_evidence"),
        "risk": state.get("risk_evidence")
    }
    
    messages = [
        SystemMessage(content=CRITIC_PROMPT),
        HumanMessage(content=f"Compiled Evidence:\n{json.dumps(evidence_bundle, default=str)}")
    ]
    
    response = llm.invoke(messages)
    
    try:
        content = response.content
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0].strip()
        elif "```" in content:
            content = content.split("```")[1].strip()
            
        parsed = json.loads(content)
        feedback = parsed.get("critic_feedback", "No feedback.")
        is_valid = bool(parsed.get("is_valid", True))
    except Exception as e:
        feedback = f"Failed to parse critic feedback. Error: {str(e)}"
        is_valid = True  # Default to true on parser failure so pipeline doesn't completely die
        
    return {
        "critic_feedback": feedback,
        "is_valid": is_valid
    }
