"use client";

import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <div style={{ padding: "48px 64px", maxWidth: 900, margin: "0 auto", color: "var(--text-primary)" }}>
      <div style={{ marginBottom: 40 }}>
        <h1 style={{ fontSize: 36, fontWeight: 900, letterSpacing: "-0.03em", marginBottom: 12 }}>
          Regulatory Disclaimer & Terms of Use
        </h1>
        <p style={{ fontSize: 16, color: "var(--text-secondary)", lineHeight: 1.6 }}>
          Please read this carefully before using the MakeMeRich Indian Equity Intelligence Platform. By accessing or using the platform, you agree to these terms.
        </p>
      </div>

      <div className="card" style={{ padding: "32px 40px", marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "var(--accent-red)", marginBottom: 16, display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ fontSize: 24 }}>⚖️</span> Not Investment Advice
        </h2>
        <div style={{ fontSize: 15, color: "var(--text-secondary)", lineHeight: 1.7, display: "flex", flexDirection: "column", gap: 16 }}>
          <p>
            The MakeMeRich platform is a <strong>quantitative data analysis and decision-support tool</strong>. It is designed to assist users in their own research by aggregating market data, computing technical/fundamental indicators, and providing AI-generated summaries of historical data.
          </p>
          <p>
            <strong style={{ color: "var(--text-primary)" }}>We are NOT registered with the Securities and Exchange Board of India (SEBI)</strong> as an Investment Adviser, Research Analyst, or Portfolio Manager. 
          </p>
          <p>
            No content generated by this platform—including but not limited to "Opportunity Levels", "Confidence Scores", "Entry Zones", or "Agent Debates"—should be construed as financial advice, a research report, or a recommendation to buy, sell, or hold any security.
          </p>
        </div>
      </div>

      <div style={{ display: "grid", gap: 24 }}>
        <div className="card" style={{ padding: "24px 32px" }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>Probabilistic Output & AI Limitations</h3>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6 }}>
            All analyses produced by the Multi-Agent AI Pipeline are probabilistic and based purely on historical data patterns up to the point of analysis (Point-in-Time). Artificial Intelligence models can hallucinate, misinterpret data, or fail to account for real-world macroeconomic, geopolitical, or corporate governance events. You must never execute a trade based solely on AI output.
          </p>
        </div>

        <div className="card" style={{ padding: "24px 32px" }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>Past Performance</h3>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6 }}>
            Any backtested results, strategy evaluations, or historical success rates displayed in the Backtest Lab or elsewhere on the platform are hypothetical. <strong>Past performance does not guarantee future results.</strong> Real-world trading involves slippage, taxes, brokerage fees, and liquidity constraints that are not fully modeled in backtests.
          </p>
        </div>

        <div className="card" style={{ padding: "24px 32px" }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>Data Accuracy & Delays</h3>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6 }}>
            Market data (price, volume, fundamentals) is sourced from third-party providers (Angel One, Yahoo Finance, etc.). While we strive for accuracy, we do not guarantee that the data is error-free, timely, or complete. Data may be delayed. 
          </p>
        </div>

        <div className="card" style={{ padding: "24px 32px", border: "1px solid rgba(239,68,68,0.3)", background: "rgba(239,68,68,0.05)" }}>
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 12, color: "var(--accent-red)" }}>Assumption of Risk</h3>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.6 }}>
            Trading in Indian Equities (NSE/BSE) involves significant risk of capital loss. You are solely responsible for your own investment decisions. By using this platform, you agree to hold harmless the developers, creators, and operators of MakeMeRich from any and all financial losses or damages incurred.
          </p>
        </div>
      </div>

      <div style={{ marginTop: 48, textAlign: "center" }}>
        <Link href="/" style={{ padding: "12px 24px", background: "var(--accent-blue)", color: "#fff", borderRadius: 8, fontSize: 14, fontWeight: 600, textDecoration: "none", display: "inline-block" }}>
          I Understand & Agree — Return Home
        </Link>
      </div>
    </div>
  );
}
