"""initial_schema_v1

Revision ID: 7fe488e2c76a
Revises: 
Create Date: 2026-09-16 16:21:42.890334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe488e2c76a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('action_type', sa.Enum('SPLIT', 'BONUS', 'DIVIDEND', 'RIGHTS', 'MERGER', 'DEMERGER', name='corporateactiontypeenum'), nullable=False),
    sa.Column('ex_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ratio', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corp_actions_symbol_date', 'corporate_actions', ['symbol', 'ex_date'], unique=False)
    op.create_table('data_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('to_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_periods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('revenue_yoy_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_profit_yoy_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roce', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'period_type', 'period_label', name='uq_financials_symbol_period')
    )
    op.create_index('ix_financials_symbol_date', 'financial_periods', ['symbol', 'period_end_date'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('book_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fii_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dii_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('public_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'as_of_date', name='uq_fundamentals_symbol_date')
    )
    op.create_index('ix_fundamentals_symbol', 'fundamentals', ['symbol'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('instrument_type', sa.Enum('EQ', 'ETF', 'INDEX', name='instrumenttypeenum'), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_instrument_symbol_exchange')
    )
    op.create_index('ix_instruments_sector', 'instruments', ['sector'], unique=False)
    op.create_index('ix_instruments_symbol', 'instruments', ['symbol'], unique=False)
    op.create_table('market_quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('ltp', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('change', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('quote_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_quote_symbol_exchange')
    )
    op.create_index('ix_quotes_symbol', 'market_quotes', ['symbol'], unique=False)
    op.create_table('market_regime_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nifty_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('nifty_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('nifty_ema_50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('nifty_ema_200', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('india_vix', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vix_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('advances', sa.Integer(), nullable=True),
    sa.Column('declines', sa.Integer(), nullable=True),
    sa.Column('unchanged', sa.Integer(), nullable=True),
    sa.Column('advance_decline_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('regime', sa.Enum('BULL', 'BEAR', 'NEUTRAL', 'SIDEWAYS', name='marketregimeenum'), nullable=True),
    sa.Column('regime_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index('ix_regime_date', 'market_regime_features', ['date'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('timeframe', sa.Enum('ONE_MIN', 'FIVE_MIN', 'FIFTEEN_MIN', 'THIRTY_MIN', 'ONE_HOUR', 'ONE_DAY', 'ONE_WEEK', name='timeframeenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ema_9', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema_21', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema_200', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sma_200', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_histogram', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bb_middle', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('adx_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume_ma_20', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'timeframe', 'timestamp', name='uq_ti_symbol_tf_ts')
    )
    op.create_index('ix_ti_symbol_tf_ts', 'technical_indicators', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.Enum('NSE', 'BSE', name='exchangeenum'), nullable=False),
    sa.Column('timeframe', sa.Enum('ONE_MIN', 'FIVE_MIN', 'FIFTEEN_MIN', 'THIRTY_MIN', 'ONE_HOUR', 'ONE_DAY', 'ONE_WEEK', name='timeframeenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'timeframe', 'timestamp', name='uq_candle_symbol_tf_ts')
    )
    op.create_index('ix_candles_symbol_tf_ts', 'market_candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candles_symbol_tf_ts', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index('ix_ti_symbol_tf_ts', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index('ix_regime_date', table_name='market_regime_features')
    op.drop_table('market_regime_features')
    op.drop_index('ix_quotes_symbol', table_name='market_quotes')
    op.drop_table('market_quotes')
    op.drop_index('ix_instruments_symbol', table_name='instruments')
    op.drop_index('ix_instruments_sector', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('ix_fundamentals_symbol', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index('ix_financials_symbol_date', table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_table('data_versions')
    op.drop_index('ix_corp_actions_symbol_date', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
