"""Add RecommendationSnapshot

Revision ID: a234a84cb119
Revises: 7fe488e2c76a
Create Date: 2026-09-16 17:32:27.722169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a234a84cb119'
down_revision: Union[str, Sequence[str], None] = '7fe488e2c76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('opportunity_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('time_horizon', sa.String(length=50), nullable=False),
    sa.Column('opportunity_state_json', sa.JSON(), nullable=False),
    sa.Column('agent_evidence_json', sa.JSON(), nullable=False),
    sa.Column('critic_feedback', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_symbol_date', 'recommendation_snapshots', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_symbol_date', table_name='recommendation_snapshots')
    op.drop_table('recommendation_snapshots')
    # ### end Alembic commands ###
