"""add_production_audit_tables

Revision ID: dbc50d38bb56
Revises: a234a84cb119
Create Date: 2026-09-17 01:56:34.791847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'dbc50d38bb56'
down_revision: Union[str, Sequence[str], None] = 'a234a84cb119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_depth_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_buy_qty', sa.BigInteger(), nullable=True),
    sa.Column('total_sell_qty', sa.BigInteger(), nullable=True),
    sa.Column('bid_ask_spread', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('depth_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_depth_symbol_ts', 'market_depth_snapshots', ['symbol', 'timestamp'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('provider_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_table('relative_strength_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rs_vs_nifty_5d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rs_vs_nifty_20d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rs_vs_nifty_60d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rs_vs_sector_20d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_classifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('basic_industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sector_class_symbol', 'sector_classifications', ['symbol'], unique=False)
    op.create_table('shareholding_patterns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fii_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dii_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('public_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mutual_fund_holding_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pledged_promoter_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shareholding_symbol_date', 'shareholding_patterns', ['symbol', 'as_of_date'], unique=False)
    op.create_table('valuation_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peg_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('earnings_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fcf_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sector_pe_percentile', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sector_pb_percentile', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_val_feat_symbol_ts', 'valuation_features', ['symbol', 'timestamp'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('model_version_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.version_id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('critic_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', postgresql.ENUM('NSE', 'BSE', name='exchangeenum', create_type=False), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'exchange', name='uq_portfolio_item')
    )
    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_type', sa.String(length=20), nullable=False),
    sa.Column('price_at_recommendation', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_at_target', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('lowest_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('hit_invalidation', sa.Boolean(), nullable=False),
    sa.Column('hit_target', sa.Boolean(), nullable=False),
    sa.Column('net_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('nifty_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_claims',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_claim_id', sa.BigInteger(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.String(length=255), nullable=False),
    sa.Column('data_source_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['agent_claim_id'], ['agent_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_evidence')
    op.drop_table('agent_claims')
    op.drop_table('recommendation_outcomes')
    op.drop_table('portfolios')
    op.drop_table('critic_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_val_feat_symbol_ts', table_name='valuation_features')
    op.drop_table('valuation_features')
    op.drop_index('ix_shareholding_symbol_date', table_name='shareholding_patterns')
    op.drop_table('shareholding_patterns')
    op.drop_index('ix_sector_class_symbol', table_name='sector_classifications')
    op.drop_table('sector_classifications')
    op.drop_table('relative_strength_features')
    op.drop_table('model_versions')
    op.drop_index('ix_market_depth_symbol_ts', table_name='market_depth_snapshots')
    op.drop_table('market_depth_snapshots')
    # ### end Alembic commands ###
