from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc
from datetime import datetime, date

from core.database import get_db
from models.models import RecommendationSnapshot

router = APIRouter(prefix="/opportunities", tags=["opportunities"])

@router.get("/today")
async def get_todays_opportunities(
    db: AsyncSession = Depends(get_db),
    limit: int = Query(default=50)
):
    """
    Get the latest opportunities generated by the V3 Engine.
    """
    # Assuming today's date for simplicity; in a real app you'd filter by timestamp >= start_of_day
    stmt = (
        select(RecommendationSnapshot)
        .where(RecommendationSnapshot.is_active == True)
        .order_by(desc(RecommendationSnapshot.timestamp))
        .limit(limit)
    )
    result = await db.execute(stmt)
    snapshots = result.scalars().all()
    
    return [
        {
            "id": s.id,
            "symbol": s.symbol,
            "timestamp": s.timestamp,
            "current_price": s.current_price,
            "opportunity_level": s.opportunity_level,
            "confidence": s.confidence,
            "risk_level": s.risk_level,
            "time_horizon": s.time_horizon,
            "opportunity_state": s.opportunity_state_json
        }
        for s in snapshots
    ]

@router.get("/{id}")
async def get_opportunity_details(
    id: int,
    db: AsyncSession = Depends(get_db)
):
    """
    Get the full auditable details of a specific opportunity, including all agent evidence.
    """
    snapshot = await db.get(RecommendationSnapshot, id)
    if not snapshot:
        raise HTTPException(status_code=404, detail="Opportunity not found")
        
    return {
        "id": snapshot.id,
        "symbol": snapshot.symbol,
        "timestamp": snapshot.timestamp,
        "current_price": snapshot.current_price,
        "opportunity_level": snapshot.opportunity_level,
        "confidence": snapshot.confidence,
        "risk_level": snapshot.risk_level,
        "time_horizon": snapshot.time_horizon,
        "opportunity_state": snapshot.opportunity_state_json,
        "agent_evidence": snapshot.agent_evidence_json,
        "critic_feedback": snapshot.critic_feedback
    }
